/-
  RGF2.lean   (module `RGF2`) — the RGF 2.0 internal set theory, layered index.

  This aggregator re-exports the whole RGF 2.0 stack, organised into explicit
  logical layers.  Importing `RGF2` pulls in every layer below.

  Layer 0 — encoding domain (`RGF2/Core/`):
    * `RGF2.Core.WType`          the W-type pre-set universe `RGFPreSet`, its
                                 hereditary bisimulation quotient `RGFSet₂`, the
                                 equivalence `RGFSet₂ ≃ ZFSet`, and a proof that
                                 `(RGFSet₂, Mem₂)` satisfies the ZFC axioms.
    * `RGF2.Core.SymmDiffGroup`  a genuine (commutative) group living inside the
                                 internal universe: symmetric difference on
                                 `RGFSet₂`.  (Internal re-implementation of the
                                 standard Boolean group on a power set.)
    * `RGF2.Core.InternalOrdinal`  internal ordinal arithmetic: the von Neumann
                                 ordinals as internal objects, with ∈ = `<`,
                                 ⊆ = `≤`, successor, addition and multiplication
                                 transported from Mathlib, plus the
                                 non-commutativity witness `1 + ω = ω ≠ ω + 1`.
                                 (Internal re-implementation of a standard
                                 construction — not new mathematics.)
    * `RGF2.Core.InternalCardinal`  internal cardinal comparison: internal
                                 cardinality, `≤`/equinumerosity, the internal
                                 power-set object, and **Cantor's theorem**
                                 `|a| < |P(a)|` internally.  (Internal
                                 re-implementation of a standard construction.)

  Layer 1 — structures over the universe (`RGF2/Hierarchy/`, `RGF2/Boolean/`):
    * `RGF2.Hierarchy.Cumulative`   the von Neumann cumulative hierarchy `Vhier`,
                                    internal `rank₂`, monotonicity, transitivity,
                                    exhaustion, reflection, the **limit-stage union
                                    equation** `V_λ = ⋃_{β<λ} V_β`, the internal set
                                    operations and the **arithmetic of `rank₂`**.
    * `RGF2.Hierarchy.Reflection`   the **Montague–Lévy reflection principle**
                                    (closure form): arbitrarily large limit stages
                                    are closed under any internal class function.
    * `RGF2.Hierarchy.HereditarilyFinite`  the exact interface with RGF 1.0:
                                    `V_ω` is precisely the hereditarily-finite core,
                                    with a membership-preserving bijection to the
                                    Ackermann codes `ℕ` (`Vomega_is_RGF1_core`).
    * `RGF2.Hierarchy.Transfinite` transfinite recursion / iteration, the Hartogs
                                   function, well-ordering and choice.
    * `RGF2.Boolean.Model`         the boolean-valued universe `BSet B`, its
                                   `B`-valued equality/membership and soundness.
    * `RGF2.Boolean.Forcing`       the forcing backbone: `BEq` is a `B`-valued
                                   equivalence relation, Leibniz congruence, the
                                   Boolean-valued pairing axiom, and realised
                                   undecidability (`bmem_undecided`).
    * `RGF2.Boolean.ValuedZFC`     the core ZFC axioms validated in `V^B` at Boolean
                                   value `⊤` (Extensionality, Empty, Pairing, Union,
                                   Power set, Separation, Foundation, Infinity),
                                   bundled as `VB_models_ZFC_core`.

  Layer 2 — capstone (`RGF2/`):
    * `RGF2.Master`             assembles the four paths into the statement that
                               `(RGFSet₂, Mem₂)` models full ZFC and that the
                               upgrade over the RGF 1.0 hereditarily-finite core
                               is strict.
    * `RGF2.GenerativeBridge`   bridge theorem tying the generative
                               step-iteration dynamics (`tfIterate` / `Nat.iterate`)
                               to the internal set universe: iterating the internal
                               von Neumann successor from `∅` reproduces the
                               internal finite ordinals, and the internal `ω` is
                               exactly the orbit generated by the step dynamics
                               (`mem_omegaOrd₂_iff_iterate`).
-/
import RGF.Math.SetTheory.RGF2.Core.WType
import RGF.Math.SetTheory.RGF2.Core.SymmDiffGroup
import RGF.Math.SetTheory.RGF2.Core.InternalOrdinal
import RGF.Math.SetTheory.RGF2.Core.InternalCardinal
import RGF.Math.SetTheory.RGF2.GenerativeBridge
import RGF.Math.SetTheory.RGF2.Hierarchy.Cumulative
import RGF.Math.SetTheory.RGF2.Hierarchy.Reflection
import RGF.Math.SetTheory.RGF2.Hierarchy.HereditarilyFinite
import RGF.Math.SetTheory.RGF2.Hierarchy.Transfinite
import RGF.Math.SetTheory.RGF2.Hierarchy.Inaccessible
import RGF.Math.SetTheory.RGF2.Boolean.Model
import RGF.Math.SetTheory.RGF2.Boolean.Forcing
import RGF.Math.SetTheory.RGF2.Boolean.ValuedZFC
import RGF.Math.SetTheory.RGF2.Boolean.ForcingRelation
import RGF.Math.SetTheory.RGF2.Boolean.ChoiceReplacement
import RGF.Math.SetTheory.RGF2.Boolean.IndependenceFamily
import RGF.Math.SetTheory.RGF2.Master
