import Mathlib
import RGF.Math.Algebra.CoxeterOrdersExp
import RGF.Math.Algebra.CoxeterOrderB3
import RGF.Math.Algebra.CoxeterOrderH3

/-!
# Formalization of five-fold symmetry and the non-crystallographic Coxeter groups (H3, H4)

This file formalizes the "complete set of propositions" supplied by the user,
organized around the edge label `5` appearing in a Coxeter matrix (i.e. the
reflection angle `π/5`, the source of five-fold symmetry).

Main contents and their actual provability:

* **Part I** (infrastructure): we reuse Mathlib's `CoxeterMatrix` infrastructure
  directly (`CoxeterMatrix.H₃`, `CoxeterMatrix.H₄`, etc.) and verify that the
  user-written matrices `CoxeterMatrixH3`, `CoxeterMatrixH4` agree entrywise with
  Mathlib's standard matrices.

* **Part II, §2.2** (existence of an order-5 element): **fully proved**. The key
  construction maps the abstract Coxeter group, via `CoxeterSystem.lift`, into a
  geometric reflection representation over the finite field `ZMod 11` (`√5` exists
  in `𝔽₁₁`, taking `√5 = 4`, `2cos(π/5) = φ = 8`). This homomorphism sends the
  product of the pair of simple reflections labelled `5` to a matrix over `𝔽₁₁`
  that genuinely has order 5, thereby proving that the product has order exactly 5
  in the group.

* **Part II, §2.3** (A3, B3 have no order-5 element): **fully proved**. Since
  Mathlib contains no finiteness/cardinality theorem for `CoxeterMatrix.Group`,
  we build the missing machinery from scratch: for each of A₃ and B₃ we exhibit an
  explicit finite *covering set* of reduced words closed under left multiplication
  by the simple reflections (using a complete string-rewriting system for the
  group), which forces the abstract presentation group to be finite and bounds its
  order from above; a faithful (signed) permutation representation supplies the
  matching lower bound. This yields `|W_A3| = 24` and `|W_B3| = 48`
  (`RGF.CoxeterOrdersExp.card_A3`, `RGF.CoxeterOrderB3.card_B3`), whence no
  element has order 5 (Lagrange, `5 ∤ 24` and `5 ∤ 48`).

* **Part II, §2.1** (group orders `|W_H3| = 120`, `|W_H4| = 14400`): `|W_H3| = 120`
  is now **fully proved** (see `RGF.Math.Algebra.CoxeterOrderH3.card_H3`) by the
  same covering-set + complete-rewriting-system method used for A₃/B₃: a 120-word
  covering finset closed under left multiplication (giving `Nat.card ≤ 120`) plus a
  faithful `Perm (Fin 12)` action (giving the matching lower bound). `|W_H4| = 14400`
  remains **open**: Mathlib still contains no general finiteness/cardinality theorem
  for `CoxeterMatrix.Group` (nor parabolic-subgroup machinery), and a direct
  covering-set enumeration of 14400 elements is prohibitively large, so that single
  group-order fact remains an annotated `sorry`.

* **Parts III and IV** (classification and exclusivity): **fully proved**.
  Following the user's suggestion to "list the Coxeter data of the eleven types by
  hand and rely only on enumeration verification", these are implemented without
  depending on the abstract classification theorem itself. The user's statement
  3.2 is **honestly corrected** here (see the note below).
-/

namespace RGF.CoxeterFiveFold

open CoxeterMatrix CoxeterSystem

/-! ## Part I: infrastructure -/

/-- The standard Coxeter matrix of H3 (the icosahedral group): two edges labelled 3 and 5. -/
def CoxeterMatrixH3 : Matrix (Fin 3) (Fin 3) ℕ :=
  !![1, 3, 2; 3, 1, 5; 2, 5, 1]

/-- The standard Coxeter matrix of H4 (the 600-cell group). -/
def CoxeterMatrixH4 : Matrix (Fin 4) (Fin 4) ℕ :=
  !![1, 3, 2, 2; 3, 1, 3, 2; 2, 3, 1, 5; 2, 2, 5, 1]

/-- The user-written H3 matrix agrees entrywise with Mathlib's standard
`CoxeterMatrix.H₃` (faithfulness check). -/
theorem CoxeterMatrixH3_eq : (CoxeterMatrix.H₃ : Matrix (Fin 3) (Fin 3) ℕ) = CoxeterMatrixH3 := by
  decide

/-- The user-written H4 matrix agrees entrywise with Mathlib's standard
`CoxeterMatrix.H₄` (faithfulness check). -/
theorem CoxeterMatrixH4_eq : (CoxeterMatrix.H₄ : Matrix (Fin 4) (Fin 4) ℕ) = CoxeterMatrixH4 := by
  decide

/-- The (presentation) group generated by the Coxeter matrix of H3. -/
abbrev W_H3 : Type := CoxeterMatrix.H₃.Group
/-- The (presentation) group generated by the Coxeter matrix of H4. -/
abbrev W_H4 : Type := CoxeterMatrix.H₄.Group

/-- The Coxeter group of A3 (the tetrahedral group, rank 3, $\cong S_4$). -/
abbrev W_A3 : Type := (CoxeterMatrix.Aₙ 3).Group
/-- The Coxeter group of B3 (the octahedral group, rank 3). -/
abbrev W_B3 : Type := (CoxeterMatrix.Bₙ 3).Group

/-! ## Part II, §2.2: existence of an order-5 element (fully proved)

Construction idea: map the Coxeter group to a geometric reflection representation
over `ZMod 11`. Since `4² = 5 (mod 11)`, we have `√5 = 4` and
`φ = 2cos(π/5) = (1+√5)/2 = 8 (mod 11)`. The reflection matrix `sᵢ` is the
identity except in row `i`; the diagonal entry of row `i` is `-1`, and the
off-diagonal entry `(i,j)` is `2cos(π/mᵢⱼ)` (`m=2→0, m=3→1, m=5→8`).
-/

/-- The finite field `𝔽₁₁`. -/
abbrev R11 := ZMod 11

/-- The geometric reflection representation of H3 (3×3 matrices over `𝔽₁₁`). -/
def repH3 : Fin 3 → Matrix (Fin 3) (Fin 3) R11 :=
  ![ !![-1, 1, 0; 0, 1, 0; 0, 0, 1],
     !![ 1, 0, 0; 1, -1, 8; 0, 0, 1],
     !![ 1, 0, 0; 0, 1, 0; 0, 8, -1] ]

theorem hliftH3 : IsLiftable CoxeterMatrix.H₃ repH3 := by
  intro i i'; fin_cases i <;> fin_cases i' <;> decide

/-- **Existence of an order-5 element (H3)**: `W_H3` contains an element of order
5, coming directly from the edge label `5`. -/
theorem W_H3_has_order5_element : ∃ g : W_H3, orderOf g = 5 := by
  set cs := CoxeterMatrix.H₃.toCoxeterSystem
  refine ⟨cs.simple 1 * cs.simple 2, ?_⟩
  have hpow : (cs.simple 1 * cs.simple 2) ^ 5 = 1 := by
    have h := cs.simple_mul_simple_pow 1 2
    have h5 : (CoxeterMatrix.H₃ : Matrix (Fin 3) (Fin 3) ℕ) 1 2 = 5 := by decide
    rwa [h5] at h
  have key : (cs.lift ⟨repH3, hliftH3⟩) (cs.simple 1 * cs.simple 2) = repH3 1 * repH3 2 := by
    rw [map_mul, cs.lift_apply_simple, cs.lift_apply_simple]
  have hne1 : (cs.simple 1 * cs.simple 2) ≠ 1 := by
    intro h
    rw [h, map_one] at key
    have : repH3 1 * repH3 2 ≠ (1 : Matrix (Fin 3) (Fin 3) R11) := by decide
    exact this key.symm
  haveI : Fact (Nat.Prime 5) := ⟨by norm_num⟩
  exact orderOf_eq_prime hpow hne1

/-- The geometric reflection representation of H4 (4×4 matrices over `𝔽₁₁`). -/
def repH4 : Fin 4 → Matrix (Fin 4) (Fin 4) R11 :=
  ![ !![-1, 1, 0, 0; 0, 1, 0, 0; 0, 0, 1, 0; 0, 0, 0, 1],
     !![ 1, 0, 0, 0; 1, -1, 1, 0; 0, 0, 1, 0; 0, 0, 0, 1],
     !![ 1, 0, 0, 0; 0, 1, 0, 0; 0, 1, -1, 8; 0, 0, 0, 1],
     !![ 1, 0, 0, 0; 0, 1, 0, 0; 0, 0, 1, 0; 0, 0, 8, -1] ]

theorem hliftH4 : IsLiftable CoxeterMatrix.H₄ repH4 := by
  intro i i'; fin_cases i <;> fin_cases i' <;> decide

/-- **Existence of an order-5 element (H4)**: `W_H4` contains an element of order 5. -/
theorem W_H4_has_order5_element : ∃ g : W_H4, orderOf g = 5 := by
  set cs := CoxeterMatrix.H₄.toCoxeterSystem
  refine ⟨cs.simple 2 * cs.simple 3, ?_⟩
  have hpow : (cs.simple 2 * cs.simple 3) ^ 5 = 1 := by
    have h := cs.simple_mul_simple_pow 2 3
    have h5 : (CoxeterMatrix.H₄ : Matrix (Fin 4) (Fin 4) ℕ) 2 3 = 5 := by decide
    rwa [h5] at h
  have key : (cs.lift ⟨repH4, hliftH4⟩) (cs.simple 2 * cs.simple 3) = repH4 2 * repH4 3 := by
    rw [map_mul, cs.lift_apply_simple, cs.lift_apply_simple]
  have hne1 : (cs.simple 2 * cs.simple 3) ≠ 1 := by
    intro h
    rw [h, map_one] at key
    have : repH4 2 * repH4 3 ≠ (1 : Matrix (Fin 4) (Fin 4) R11) := by decide
    exact this key.symm
  haveI : Fact (Nat.Prime 5) := ⟨by norm_num⟩
  exact orderOf_eq_prime hpow hne1

/-! ## Part II, §2.1: group orders of the icosahedral Coxeter groups

The A₃, B₃ and H₃ group orders are established (see `RGF.CoxeterOrdersExp`,
`RGF.CoxeterOrderB3` and `RGF.CoxeterOrderH3`) by an explicit covering-set +
complete-rewriting-system argument.  The same method applies to H₄ (14400) in
principle, but a 14400-element enumeration is prohibitively large, so `card_W_H4`
below remains the single documented open `sorry`.
-/

/-- Group order `|W_H3| = 120`.  Now **fully proved** in
`RGF.Math.Algebra.CoxeterOrderH3` by the covering-set + complete-rewriting-system
method (the 120 reduced words, closed under left multiplication by the simple
reflections; lower bound from a faithful `Perm (Fin 12)` action). -/
theorem card_W_H3 : Nat.card W_H3 = 120 :=
  RGF.CoxeterOrderH3.card_H3

/-- Group order `|W_H4| = 14400`. **OPEN**: the covering-set method would require a
14400-element enumeration, which is not formalized here. -/
theorem card_W_H4 : Nat.card W_H4 = 14400 := by
  sorry

/-- Control group: A3 ($\cong S_4$, order 24) has no order-5 element. Proved via
`RGF.CoxeterOrdersExp.card_A3` (`|W_A3| = 24`, established by an explicit covering
finset and the S₄ rewriting system) together with Lagrange's theorem. -/
theorem W_A3_no_order5 : ∀ g : W_A3, orderOf g ≠ 5 :=
  RGF.CoxeterOrdersExp.W_A3_no_order5

/-- Control group: B3 (order 48) has no order-5 element. Proved via
`RGF.CoxeterOrderB3.card_B3` (`|W_B3| = 48`) together with Lagrange's theorem. -/
theorem W_B3_no_order5 : ∀ g : W_B3, orderOf g ≠ 5 :=
  RGF.CoxeterOrderB3.W_B3_no_order5

/-! ## Part III: classification data of finite irreducible Coxeter groups (enumeration-verification route)

(Note: the `A3_no_five`, `B3_no_five` below are the honest counterparts of §2.3
that are **fully provable** within this enumeration framework: the Coxeter
matrices of the crystallographically allowed types A3 and B3 contain no edge label
`5`, which is precisely the combinatorial reason they lack five-fold symmetry.) -/

/-- The complete classification list of finite irreducible Coxeter groups
(Coxeter 1935). -/
inductive FiniteIrreducibleCoxeterType : Type
  | A (n : ℕ) (h : 1 ≤ n)
  | B (n : ℕ) (h : 2 ≤ n)
  | D (n : ℕ) (h : 4 ≤ n)
  | E6 | E7 | E8
  | F4
  | G2
  | H3 | H4
  | I2 (m : ℕ) (h : 5 ≤ m)   -- planar dihedral family, exists for every m ≥ 5

open FiniteIrreducibleCoxeterType

/-- The Coxeter label of each type at position `(i,j)`. Each literal reproduces a
standard Coxeter-matrix entry; for the classification we care about, the only
point is that the value `5` occurs solely in `H3`, `H4`, `I2 5`.
(For E6/E7/E8 it suffices that their entries take values in `{1,2,3}`; here they
are given by a path-graph pattern, which is enough to decide "no 5".) -/
def CoxeterMatrixOf : FiniteIrreducibleCoxeterType → ℕ → ℕ → ℕ
  | A _ _, i, j => if i = j then 1 else if i + 1 = j ∨ j + 1 = i then 3 else 2
  | B n _, i, j => if i = j then 1
                   else if (i = n - 1 ∧ j = n - 2) ∨ (j = n - 1 ∧ i = n - 2) then 4
                   else if i + 1 = j ∨ j + 1 = i then 3 else 2
  | D n _, i, j => if i = j then 1
                   else if (i = n - 1 ∧ j = n - 3) ∨ (j = n - 1 ∧ i = n - 3) then 3
                   else if i + 1 = j ∨ j + 1 = i then 3 else 2
  | E6, i, j => if i = j then 1 else if i + 1 = j ∨ j + 1 = i then 3 else 2
  | E7, i, j => if i = j then 1 else if i + 1 = j ∨ j + 1 = i then 3 else 2
  | E8, i, j => if i = j then 1 else if i + 1 = j ∨ j + 1 = i then 3 else 2
  | F4, i, j => if i = j then 1 else if (i = 1 ∧ j = 2) ∨ (i = 2 ∧ j = 1) then 4
                else if i + 1 = j ∨ j + 1 = i then 3 else 2
  | G2, i, j => if i = j then 1 else 6
  | H3, i, j => if i = j then 1 else if (i = 1 ∧ j = 2) ∨ (i = 2 ∧ j = 1) then 5
                else if (i = 0 ∧ j = 1) ∨ (i = 1 ∧ j = 0) then 3 else 2
  | H4, i, j => if i = j then 1 else if (i = 2 ∧ j = 3) ∨ (i = 3 ∧ j = 2) then 5
                else if i + 1 = j ∨ j + 1 = i then 3 else 2
  | I2 m _, i, j => if i = j then 1 else if i < 2 ∧ j < 2 then m else 2

/-- The rank of a type (number of simple reflections = dimension of the space). -/
def rankOf : FiniteIrreducibleCoxeterType → ℕ
  | A n _ => n | B n _ => n | D n _ => n
  | E6 => 6 | E7 => 7 | E8 => 8 | F4 => 4 | G2 => 2 | H3 => 3 | H4 => 4
  | I2 _ _ => 2

/-- Key lemma: a type contains the edge label `5` if and only if it is `H3`, `H4`,
or `I2 5`. -/
theorem hasFive_iff (T : FiniteIrreducibleCoxeterType) :
    (∃ i j, CoxeterMatrixOf T i j = 5) ↔
      (T = H3 ∨ T = H4 ∨ T = I2 5 (le_refl 5)) := by
  constructor
  · rintro ⟨i, j, hij⟩
    cases T with
    | A n h => simp only [CoxeterMatrixOf] at hij; split_ifs at hij <;> omega
    | B n h => simp only [CoxeterMatrixOf] at hij; split_ifs at hij <;> omega
    | D n h => simp only [CoxeterMatrixOf] at hij; split_ifs at hij <;> omega
    | E6 => simp only [CoxeterMatrixOf] at hij; split_ifs at hij <;> omega
    | E7 => simp only [CoxeterMatrixOf] at hij; split_ifs at hij <;> omega
    | E8 => simp only [CoxeterMatrixOf] at hij; split_ifs at hij <;> omega
    | F4 => simp only [CoxeterMatrixOf] at hij; split_ifs at hij <;> omega
    | G2 => simp only [CoxeterMatrixOf] at hij; split_ifs at hij <;> omega
    | H3 => exact Or.inl rfl
    | H4 => exact Or.inr (Or.inl rfl)
    | I2 m h =>
        simp only [CoxeterMatrixOf] at hij
        split_ifs at hij with h1 h2
        · omega
        · subst hij; exact Or.inr (Or.inr rfl)
        · omega
  · rintro (rfl | rfl | rfl)
    · exact ⟨1, 2, rfl⟩
    · exact ⟨2, 3, rfl⟩
    · exact ⟨0, 1, rfl⟩

/-- **3.2 The complete list of types carrying "5" (corrected version of the user's
statement).**

The user's original statement
```
(∃ i j, CoxeterMatrixOf T i j = 5) ↔ (T = .H3 ∨ T = .H4 ∨ ∃ m ≥ 5, T = .I2 m)
```
is **incorrect**: for example `I2 7` satisfies the right-hand side
(`∃ m ≥ 5, T = I2 m`) yet contains no `5` (its unique edge label is `7`). The
correct characterization restricts the dihedral branch to `I2 5`; see
`hasFive_iff`. -/
theorem five_edge_label_classification (T : FiniteIrreducibleCoxeterType) :
    (∃ i j, CoxeterMatrixOf T i j = 5) ↔
      (T = H3 ∨ T = H4 ∨ T = I2 5 (le_refl 5)) :=
  hasFive_iff T

/-- **3.3 Key restriction: for rank ≥ 3, "5" occurs only in exactly the two
exceptional types H3, H4.** -/
theorem five_exception_rank_geq_3 (T : FiniteIrreducibleCoxeterType) (hrank : 3 ≤ rankOf T) :
    (∃ i j, CoxeterMatrixOf T i j = 5) ↔ (T = H3 ∨ T = H4) := by
  rw [hasFive_iff]
  constructor
  · rintro (rfl | rfl | rfl)
    · exact Or.inl rfl
    · exact Or.inr rfl
    · simp only [rankOf] at hrank; omega   -- the rank of I2 5 is 2 < 3, contradiction
  · rintro (rfl | rfl)
    · exact Or.inl rfl
    · exact Or.inr (Or.inl rfl)

/-- **Honest counterpart of §2.3 within the enumeration framework (A3)**: the
Coxeter matrix of the crystallographically allowed type A3 contains no edge label
`5`. -/
theorem A3_no_five : ¬ ∃ i j, CoxeterMatrixOf (A 3 (by norm_num)) i j = 5 := by
  rw [hasFive_iff]; rintro (h | h | h) <;> cases h

/-- **Honest counterpart of §2.3 within the enumeration framework (B3)**: the
Coxeter matrix of the crystallographically allowed type B3 contains no edge label
`5`. -/
theorem B3_no_five : ¬ ∃ i j, CoxeterMatrixOf (B 3 (by norm_num)) i j = 5 := by
  rw [hasFive_iff]; rintro (h | h | h) <;> cases h

/-! ## Part IV: the core target propositions (honest version) -/

/-- **4.1 Exclusivity main theorem: for rank ≥ 3, "5" occurs in exactly dimensions
3 and 4 (i.e. H3 and H4).**

Expected and proved result: this set equals `{3, 4}`, not the singleton `{3}`. -/
theorem five_exceptional_dims :
    { n : ℕ | 3 ≤ n ∧ ∃ T : FiniteIrreducibleCoxeterType,
        rankOf T = n ∧ (∃ i j, CoxeterMatrixOf T i j = 5) } = {3, 4} := by
  ext n
  simp only [Set.mem_setOf_eq, Set.mem_insert_iff, Set.mem_singleton_iff]
  constructor
  · rintro ⟨hn, T, hr, hfive⟩
    rw [hasFive_iff] at hfive
    rcases hfive with (rfl | rfl | rfl)
    · left; simp only [rankOf] at hr; omega
    · right; simp only [rankOf] at hr; omega
    · simp only [rankOf] at hr; omega
  · rintro (rfl | rfl)
    · exact ⟨le_refl 3, H3, rfl, 1, 2, rfl⟩
    · exact ⟨by norm_num, H4, rfl, 2, 3, rfl⟩

/-- **4.2 An additional criterion to single out n = 3.**

As the user notes: to also exclude H4 (four-dimensional) and thereby single out
`n = 3`, one needs a criterion **independent of this classification theorem**. No
such mathematical reason is currently known; this is the honest gap that this
group of propositions explicitly acknowledges. Hence the formal statement here is
merely the trivial `True` (asserting nothing about "excluding H4"). -/
theorem exclude_H4_dimension_four : True := trivial

end RGF.CoxeterFiveFold
