/-
  Foundations/RGFGenerativeConstants.lean

  Fully internal ("generative") construction of the three flagship constants
  `√2`, `π` and `e` as RGF reals.

  Motivation.  In `Foundations/RGFRealExamples.lean` the constants `√2`, `π`, `e`
  were obtained through `ofReal`, i.e. by reading off the decimal expansion of the
  *already given* standard real (`Real.sqrt 2`, `Real.pi`, `Real.exp 1`).  While
  mathematically correct, this "imports" the value from the outside rather than
  *generating* it from within the RGF framework.  This file removes that blemish:
  each constant is produced by an explicit internal iterative/series process
  operating purely on RGF rationals, with no reference to the target real in its
  definition.

    * `√2` is generated by the **Newton iteration** `xₙ₊₁ = (xₙ + 2/xₙ)/2`,
      starting from `x₀ = 1` (a recursively defined sequence of rationals).
    * `e`  is generated by the **factorial series** `∑_{k<n} 1/k!`.
    * `π`  is generated by the **Leibniz series** `4·∑_{k<n} (-1)ᵏ/(2k+1)`.

  For each we prove that its canonical image under `toReal` is the expected
  standard real (a *correctness* statement, used only to certify the limit, never
  in the generating definition), and that the generated `√2` squares to `2` inside
  `RGFReal'`.

  The bridge from a purely rational generating process to an RGF real goes through
  two reusable lemmas:

    * `isCauSeq_of_tendsto` — a rational sequence whose real embedding converges is
      Cauchy (so it determines a genuine RGF real);
    * `mk_of_tendsto`       — the canonical image of that RGF real is precisely the
      limit of the embedded sequence.
-/
import Mathlib
import RGF.Math.Real.RGFRealExamples

namespace RGF

open RGFNat RGFInt
open Filter Topology

namespace RGFReal'

/-! ## Generic bridge: from a convergent rational process to an RGF real -/

/-- A rational sequence whose real embedding converges is a `ℚ`-Cauchy sequence. -/
theorem isCauSeq_of_tendsto (g : ℕ → ℚ) (L : ℝ)
    (h : Tendsto (fun n => ((g n : ℚ) : ℝ)) atTop (𝓝 L)) : IsCauSeq abs g := by
  have hcau : CauchySeq (fun n => ((g n : ℚ) : ℝ)) := h.cauchySeq
  rw [Metric.cauchySeq_iff] at hcau
  intro ε hε
  obtain ⟨i, hi⟩ := hcau ε (by exact_mod_cast hε)
  refine ⟨i, fun j hj => ?_⟩
  have h2 := hi j hj i (le_refl i)
  rw [Real.dist_eq] at h2
  have h3 : |((g j - g i : ℚ) : ℝ)| < ((ε : ℚ) : ℝ) := by push_cast; convert h2 using 2
  rw [show |((g j - g i : ℚ) : ℝ)| = (((|g j - g i| : ℚ)) : ℝ) by rw [Rat.cast_abs]] at h3
  exact_mod_cast h3

/-- The canonical image of `Real.mk f` is the limit of the embedded sequence. -/
theorem mk_of_tendsto (f : CauSeq ℚ abs) (L : ℝ)
    (h : Tendsto (fun n => ((f n : ℚ) : ℝ)) atTop (𝓝 L)) : Real.mk f = L := by
  have hb : ∀ ε : ℝ, 0 < ε → |Real.mk f - L| ≤ ε := by
    intro ε hε
    apply Real.mk_near_of_forall_near
    rw [Metric.tendsto_atTop] at h
    obtain ⟨i, hi⟩ := h ε hε
    exact ⟨i, fun j hj => (le_of_lt (by simpa [Real.dist_eq] using hi j hj))⟩
  have hz : |Real.mk f - L| ≤ 0 := by
    by_contra h'
    push_neg at h'
    have := hb (|Real.mk f - L| / 2) (by linarith)
    linarith
  rw [abs_nonpos_iff, sub_eq_zero] at hz
  exact hz

/-- Generate an RGF real from an internal rational process `g` whose real
    embedding converges to `L`. -/
noncomputable def ofTendsto (g : ℕ → ℚ) (L : ℝ)
    (h : Tendsto (fun n => ((g n : ℚ) : ℝ)) atTop (𝓝 L)) : RGFReal' :=
  ofRatCauSeq ⟨g, isCauSeq_of_tendsto g L h⟩

/-- The generated RGF real has the limit as its canonical image. -/
@[simp] theorem toReal_ofTendsto (g : ℕ → ℚ) (L : ℝ)
    (h : Tendsto (fun n => ((g n : ℚ) : ℝ)) atTop (𝓝 L)) :
    toReal (ofTendsto g L h) = L := by
  rw [ofTendsto, toReal_ofRatCauSeq]
  exact mk_of_tendsto _ L h

/-! ## `e` via the internal factorial series `∑_{k<n} 1/k!` -/

/-- Internal generating process for `e`: rational partial sums of `∑ 1/k!`. -/
def eGen (n : ℕ) : ℚ := ∑ k ∈ Finset.range n, (1 : ℚ) / k.factorial

theorem eGen_tendsto :
    Tendsto (fun n => ((eGen n : ℚ) : ℝ)) atTop (𝓝 (Real.exp 1)) := by
  have h := (NormedSpace.expSeries_div_hasSum_exp (1 : ℝ)).tendsto_sum_nat
  rw [← Real.exp_eq_exp_ℝ] at h
  unfold eGen
  convert h using 2 with n
  push_cast
  simp

/-- `e` generated as an RGF real from the factorial series. -/
noncomputable def rgfE : RGFReal' := ofTendsto eGen (Real.exp 1) eGen_tendsto

@[simp] theorem toReal_rgfE : toReal rgfE = Real.exp 1 := toReal_ofTendsto _ _ _

/-! ## `π` via the internal Leibniz series `4·∑_{k<n} (-1)ᵏ/(2k+1)` -/

/-- Internal generating process for `π`: rational partial sums of the Leibniz
    series, scaled by `4`. -/
def piGen (n : ℕ) : ℚ := 4 * ∑ k ∈ Finset.range n, (-1 : ℚ) ^ k / (2 * k + 1)

theorem piGen_tendsto :
    Tendsto (fun n => ((piGen n : ℚ) : ℝ)) atTop (𝓝 Real.pi) := by
  have h4 : Tendsto (fun n => 4 * ∑ i ∈ Finset.range n, (-1 : ℝ) ^ i / (2 * i + 1))
      atTop (𝓝 (4 * (Real.pi / 4))) := Real.tendsto_sum_pi_div_four.const_mul 4
  rw [show (4 : ℝ) * (Real.pi / 4) = Real.pi by ring] at h4
  unfold piGen
  convert h4 using 2 with n
  push_cast
  ring

/-- `π` generated as an RGF real from the Leibniz series. -/
noncomputable def rgfPi : RGFReal' := ofTendsto piGen Real.pi piGen_tendsto

@[simp] theorem toReal_rgfPi : toReal rgfPi = Real.pi := toReal_ofTendsto _ _ _

/-! ## `√2` via the internal Newton iteration `xₙ₊₁ = (xₙ + 2/xₙ)/2` -/

/-- Internal generating process for `√2`: the Newton (Heron) iteration on the
    rationals, starting from `1`. -/
def sqrt2Gen : ℕ → ℚ
  | 0 => 1
  | (n + 1) => (sqrt2Gen n + 2 / sqrt2Gen n) / 2

theorem sqrt2Gen_ge_one : ∀ n, 1 ≤ sqrt2Gen n := by
  intro n
  induction n with
  | zero => simp [sqrt2Gen]
  | succ k ih =>
    have hk : (0 : ℚ) < sqrt2Gen k := by linarith
    have hx : (2 : ℚ) / sqrt2Gen k * sqrt2Gen k = 2 := div_mul_cancel₀ 2 (ne_of_gt hk)
    rw [sqrt2Gen, le_div_iff₀ (by norm_num : (0 : ℚ) < 2)]
    nlinarith [sq_nonneg (sqrt2Gen k - 1), hx, hk]

theorem sqrt2Gen_pos_real (n : ℕ) : (0 : ℝ) < (sqrt2Gen n : ℝ) := by
  have := sqrt2Gen_ge_one n; exact_mod_cast lt_of_lt_of_le one_pos this

theorem sqrt2Gen_ge_one_real (n : ℕ) : (1 : ℝ) ≤ (sqrt2Gen n : ℝ) := by
  exact_mod_cast sqrt2Gen_ge_one n

theorem sqrt2Gen_rec_real (n : ℕ) :
    ((sqrt2Gen (n + 1) : ℚ) : ℝ) = ((sqrt2Gen n : ℝ) + 2 / (sqrt2Gen n : ℝ)) / 2 := by
  rw [sqrt2Gen]; push_cast; ring

theorem sqrt2Gen_ge_sqrt2 (n : ℕ) : Real.sqrt 2 ≤ (sqrt2Gen (n + 1) : ℝ) := by
  rw [sqrt2Gen_rec_real]
  have hk := sqrt2Gen_pos_real n
  have hs2 : Real.sqrt 2 ^ 2 = 2 := Real.sq_sqrt (by norm_num)
  have hsnn : (0 : ℝ) ≤ Real.sqrt 2 := Real.sqrt_nonneg 2
  rw [le_div_iff₀ (by norm_num : (0 : ℝ) < 2), ← sub_nonneg]
  have key : (sqrt2Gen n : ℝ) + 2 / (sqrt2Gen n : ℝ) - Real.sqrt 2 * 2 =
      ((sqrt2Gen n : ℝ) - Real.sqrt 2) ^ 2 / (sqrt2Gen n : ℝ) := by
    field_simp; nlinarith [hs2]
  rw [key]; positivity

/-- Quadratic convergence bound: the `(n+1)`-st Newton iterate over-estimates `√2`
    by at most `(1/2)ⁿ`. -/
theorem sqrt2Gen_err_bound (n : ℕ) :
    0 ≤ (sqrt2Gen (n + 1) : ℝ) - Real.sqrt 2 ∧
    (sqrt2Gen (n + 1) : ℝ) - Real.sqrt 2 ≤ (1 / 2) ^ n := by
  have hs2 : Real.sqrt 2 ^ 2 = 2 := Real.sq_sqrt (by norm_num)
  have hsnn : (0 : ℝ) ≤ Real.sqrt 2 := Real.sqrt_nonneg 2
  have hsle : Real.sqrt 2 ≤ 3 / 2 := by
    rw [show (3 : ℝ) / 2 = Real.sqrt ((3 / 2) ^ 2) by rw [Real.sqrt_sq (by norm_num)]]
    apply Real.sqrt_le_sqrt; norm_num
  induction n with
  | zero =>
    refine ⟨by have := sqrt2Gen_ge_sqrt2 0; linarith, ?_⟩
    simp only [pow_zero]
    have h1 : (sqrt2Gen 1 : ℝ) = 3 / 2 := by rw [sqrt2Gen_rec_real]; norm_num [sqrt2Gen]
    rw [h1]; nlinarith [hs2, hsnn]
  | succ k ih =>
    obtain ⟨ih0, ih1⟩ := ih
    have hk := sqrt2Gen_pos_real (k + 1)
    have hge1 : (1 : ℝ) ≤ (sqrt2Gen (k + 1) : ℝ) := sqrt2Gen_ge_one_real (k + 1)
    have key : (sqrt2Gen (k + 2) : ℝ) - Real.sqrt 2 =
        ((sqrt2Gen (k + 1) : ℝ) - Real.sqrt 2) ^ 2 / (2 * (sqrt2Gen (k + 1) : ℝ)) := by
      rw [sqrt2Gen_rec_real (k + 1)]; field_simp; nlinarith [hs2]
    refine ⟨by rw [key]; positivity, ?_⟩
    rw [key, div_le_iff₀ (by positivity)]
    have hpk1 : (1 / 2 : ℝ) ^ k ≤ 1 := by apply pow_le_one₀ <;> norm_num
    have hpow : (1 / 2 : ℝ) ^ (k + 1) * (2 * (sqrt2Gen (k + 1) : ℝ)) =
        (1 / 2) ^ k * (sqrt2Gen (k + 1) : ℝ) := by rw [pow_succ]; ring
    rw [hpow]
    nlinarith [ih0, ih1, hpk1, hge1,
      mul_le_mul ih1 ih1 ih0 (by positivity : (0 : ℝ) ≤ (1 / 2) ^ k)]

theorem sqrt2Gen_tendsto :
    Tendsto (fun n => ((sqrt2Gen n : ℚ) : ℝ)) atTop (𝓝 (Real.sqrt 2)) := by
  rw [← Filter.tendsto_add_atTop_iff_nat 1]
  have hsq : Tendsto (fun n => (sqrt2Gen (n + 1) : ℝ) - Real.sqrt 2) atTop (𝓝 0) := by
    apply squeeze_zero (fun n => (sqrt2Gen_err_bound n).1) (fun n => (sqrt2Gen_err_bound n).2)
    exact tendsto_pow_atTop_nhds_zero_of_lt_one (by norm_num) (by norm_num)
  have h2 := hsq.add_const (Real.sqrt 2)
  simpa using h2

/-- `√2` generated as an RGF real from the Newton iteration. -/
noncomputable def rgfSqrt2 : RGFReal' := ofTendsto sqrt2Gen (Real.sqrt 2) sqrt2Gen_tendsto

@[simp] theorem toReal_rgfSqrt2 : toReal rgfSqrt2 = Real.sqrt 2 := toReal_ofTendsto _ _ _

/-- The internally generated `√2` squares to `2` inside `RGFReal'`. -/
theorem rgfSqrt2_sq : rgfSqrt2 * rgfSqrt2 = (1 + 1 : RGFReal') := by
  apply toReal_injective
  rw [toReal_mul, toReal_add, toReal_one, toReal_rgfSqrt2]
  rw [Real.mul_self_sqrt (by norm_num)]
  norm_num

end RGFReal'
end RGF
