import Mathlib
import RGF.Physics.Emergence.LatticeUniquenessGap

/-!
# Layers 9–11: the orthogonal generation-axis rule and the second path to `d = 3`

The integrated derivation chain closes the spatial dimension at `d = 3` along two
*independent* routes that intersect at the same value:

* the **intrinsic rotation-vector criterion** `rotGen d = d ↔ d = 3`
  (formalised in `RGF.LatticeUniquenessGap`), and
* the **orthogonal generation-axis rule** of Layer 9, formalised here.

## Layer 9 — the orthogonal step rule (explicit, honest hypothesis)

The source derivation introduces, as a *first-principles axiom*, that the system
has `d` fundamental generation axes in `ℝ^d` which are mutually orthonormal and
span the whole space.  We do **not** smuggle this in as a Lean `axiom`; instead we
package it as an explicit structure `OrthoStepRule d` carrying a genuine
orthonormal family `e : Fin d → EuclideanSpace ℝ (Fin d)`, and we *derive* its
stated corollaries as theorems:

* `axes_count` — there are exactly `d` generation axes;
* `axes_span` — the axes span the whole space (so they form a basis);
* `signed_axes_injective` / `coordination_eq_two_mul` — the neighbour directions
  `{±eᵢ}` are `2d` distinct vectors, i.e. the coordination number is `z = 2d`;
* central symmetry holds by construction (the neighbour set is closed under
  negation);
* `toCandidate_forward` — the effective forward count is `2d − 1`.

## Layers 10–11 — locking and exclusion

* `ortho_locking_forces_three` (Layer 10): under the orthogonal step rule the
  locking condition `forwardCount = 5` forces `d = 3` (and `z = 6`), with no cubic
  lattice presupposed — the cubic invariants are *outputs*.
* `triangular_not_orthogonal` (Layer 11): the triangular lattice (`z = 6` in `d = 2`)
  cannot arise from an orthogonal step rule, because `z = 6 ≠ 2·2`; this is exactly
  why it shares the locking count `5` with the cubic lattice yet is excluded once
  the orthogonality axiom is imposed.

Every residual assumption (the orthogonal step rule itself) is an explicit
hypothesis/structure, never an `axiom`, in keeping with the honest-boundary
discipline of the derivation.
-/

open RGF.LatticeUniquenessGap
open scoped InnerProductSpace

namespace RGF.OrthogonalStepRule

/-- **Layer 9, as an explicit structure (not an axiom).**  The orthogonal step
    rule: the system has `d` mutually orthonormal unit generation axes living in
    `ℝ^d`. -/
structure OrthoStepRule (d : ℕ) where
  /-- The `d` generation axes. -/
  e : Fin d → EuclideanSpace ℝ (Fin d)
  /-- They are mutually orthonormal (unit length, pairwise orthogonal). -/
  orthonormal : Orthonormal ℝ e

namespace OrthoStepRule

variable {d : ℕ}

/-- **Corollary (count).**  There are exactly `d` generation axes. -/
theorem axes_count (_R : OrthoStepRule d) : Fintype.card (Fin d) = d :=
  Fintype.card_fin d

/-- **Corollary (independence).**  The generation axes are linearly independent. -/
theorem axes_linearIndependent (R : OrthoStepRule d) :
    LinearIndependent ℝ R.e :=
  R.orthonormal.linearIndependent

/-- **Corollary (spanning).**  The `d` orthonormal generation axes span the whole
    `d`-dimensional space, hence form a basis. -/
theorem axes_span (R : OrthoStepRule d) (hd : 0 < d) :
    Submodule.span ℝ (Set.range R.e) = ⊤ := by
  haveI : Nonempty (Fin d) := ⟨⟨0, hd⟩⟩
  exact (axes_linearIndependent R).span_eq_top_of_card_eq_finrank
    (by simp)

/-- The signed-axis map `Fin d ⊕ Fin d → ℝ^d`, `inl i ↦ eᵢ`, `inr i ↦ −eᵢ`,
    enumerating the `2d` candidate nearest-neighbour directions of the lattice
    generated by the orthogonal axes. -/
def signedAxis (R : OrthoStepRule d) : Fin d ⊕ Fin d → EuclideanSpace ℝ (Fin d) :=
  Sum.elim R.e (fun i => - R.e i)

/-- **Key geometric lemma.**  The `2d` signed axes `{±eᵢ}` are pairwise distinct:
    the map `signedAxis` is injective.  (Orthonormality rules out `eᵢ = eⱼ` for
    `i ≠ j`, `eᵢ = −eᵢ`, and `eᵢ = −eⱼ`.) -/
theorem signed_axes_injective (R : OrthoStepRule d) :
    Function.Injective (signedAxis R) := by
  intro x y; cases x <;> cases y <;> simp_all +decide [ Fin.ext_iff ] ;
  · have := R.orthonormal;
    exact fun h => by have := this.linearIndependent.injective h; aesop;
  · have := R.orthonormal ; simp_all +decide [ signedAxis ];
    intro h; have := this.1 ‹_›; simp_all +decide [ orthonormal_iff_ite ] ;
    rename_i i j hij; specialize hij i j; simp_all +decide ;
    split_ifs at hij <;> norm_num at hij;
  · have := R.orthonormal.2;
    rename_i i j; specialize this; simp_all +decide [ Pairwise, signedAxis ] ;
    by_contra h_contra; have := congr_arg ( fun x => ⟪x, R.e j⟫_ℝ ) h_contra; norm_num at this;
    by_cases hij : i = j <;> simp_all +decide [ R.orthonormal.1 ];
    norm_num at this;
  · simp +decide [ OrthoStepRule.signedAxis ];
    exact fun h => by simpa [ Fin.ext_iff ] using R.orthonormal.linearIndependent.injective h;

/-- **Corollary (coordination number).**  The neighbour direction set `{±eᵢ}` has
    exactly `2d` elements: the coordination number is `z = 2d`. -/
theorem coordination_eq_two_mul (R : OrthoStepRule d) :
    (Finset.univ.image (signedAxis R)).card = 2 * d := by
  rw [Finset.card_image_of_injective _ (signed_axes_injective R)]
  simp [Fintype.card_sum, two_mul]

/-- The lattice candidate induced by an orthogonal step rule: dimension `d`,
    coordination `z = 2d`, centrally symmetric (the neighbour set `{±eᵢ}` is
    closed under negation by construction). -/
def toCandidate (_R : OrthoStepRule d) : LatticeCandidate := ⟨d, 2 * d, true⟩

/-- The induced candidate is hypercubic (`z = 2·dim`). -/
theorem toCandidate_isHypercubic (R : OrthoStepRule d) :
    IsHypercubic (toCandidate R) := rfl

/-- The induced candidate is centrally symmetric. -/
theorem toCandidate_invSym (R : OrthoStepRule d) :
    (toCandidate R).invSym = true := rfl

/-- The induced candidate has dimension `d`. -/
theorem toCandidate_dim (R : OrthoStepRule d) : (toCandidate R).dim = d := rfl

/-- **Corollary (forward count).**  Under the orthogonal step rule the effective
    forward direction count is `2d − 1`. -/
theorem toCandidate_forward (R : OrthoStepRule d) :
    forwardCount (toCandidate R) = 2 * d - 1 := by
  simp [forwardCount, toCandidate]

/-- **Layer 10.**  Under the orthogonal step rule, the locking condition
    `forwardCount = 5` forces the spatial dimension to be `d = 3` — without
    presupposing a cubic lattice. -/
theorem ortho_locking_forces_three (R : OrthoStepRule d) (hd : 0 < d)
    (hlock : forwardCount (toCandidate R) = 5) : d = 3 := by
  rw [toCandidate_forward] at hlock
  omega

/-- **Layer 10 (cubic invariants).**  Under the orthogonal step rule, the locking
    condition additionally fixes the coordination number at `z = 6`. -/
theorem ortho_locking_forces_cubic (R : OrthoStepRule d) (hd : 0 < d)
    (hlock : forwardCount (toCandidate R) = 5) :
    (toCandidate R).dim = 3 ∧ (toCandidate R).coord = 6 := by
  have hd3 : d = 3 := ortho_locking_forces_three R hd hlock
  subst hd3
  exact ⟨rfl, rfl⟩

/-- **Layer 10 (self-consistency with the rotation criterion).**  At the locked
    dimension `d = 3` the intrinsic rotation-vector criterion is automatically
    satisfied, so the two independent routes agree. -/
theorem ortho_locking_rot_consistent (R : OrthoStepRule d) (hd : 0 < d)
    (hlock : forwardCount (toCandidate R) = 5) :
    rotGen (toCandidate R).dim = (toCandidate R).dim := by
  have hd3 : d = 3 := ortho_locking_forces_three R hd hlock
  subst hd3
  rw [toCandidate_dim]
  decide

end OrthoStepRule

/-- **Layer 11.**  The triangular lattice (`z = 6` at `d = 2`) is *not* realisable
    by any orthogonal step rule: an orthogonal step rule forces `z = 2·dim`, but
    the triangular lattice has `z = 6 ≠ 2·2`.  This is exactly why it shares the
    locking count `5` with the simple-cubic lattice yet is excluded once
    orthogonality is imposed. -/
theorem triangular_not_orthogonal :
    ¬ ∃ (R : OrthoStepRule triangular.dim), OrthoStepRule.toCandidate R = triangular := by
  rintro ⟨R, hR⟩
  have hco := congrArg LatticeCandidate.coord hR
  simp [OrthoStepRule.toCandidate, triangular] at hco

end RGF.OrthogonalStepRule