/-
  RGF2/GenerativeBridge.lean   (module `RGF2.GenerativeBridge`)

  **RGF 2.0 — a bridge theorem tying the generative step-iteration dynamics to the
  internal set-theoretic universe.**

  Two strands of the RGF 2.0 development have so far grown in parallel:

    * the **internal set-theory universe** `RGFSet₂` (`RGF2/Core/WType.lean`),
      where the von Neumann ordinals live as internal objects
      (`RGF2/Core/InternalOrdinal.lean`), and
    * the **generative step / iteration dynamics**, whose transfinite form is
      `tfIterate` (`RGF2/Hierarchy/Transfinite.lean`) and whose finite restriction
      is ordinary `Nat.iterate` (`tfIterate_natCast`).

  This file proves — on the finite / `ω` fragment — that these are *the same
  thing*.  Taking the internal von Neumann successor `succOrd₂` (`a ↦ a ∪ {a}`) as
  the generative step and the internal empty set `toRGFOrd 0` as the seed:

    * `iterate_succOrd₂_eq_toRGFOrd`
        iterating the step `n` times reproduces the internal finite ordinal `n`;
    * `tfIterate_succOrd₂_eq_toRGFOrd`
        consequently the *transfinite generative flow* at each finite stage `n`
        equals the internal ordinal `n` — the generative dynamics literally *is*
        the internal set-theoretic ordinal construction on this fragment;
    * `mem_omegaOrd₂_iff_iterate`
        **generation completeness for `ω`**: an internal set belongs to the
        internal `ω` iff it is some finite iterate of the step from the seed, i.e.
        the internal `ω` is *exactly* the orbit generated by the step dynamics.

  Honest scope: this is a bridge between two existing internal constructions, both
  of which are standard; it is not a claim about the physical selection layer, and
  it is deliberately confined to the finite / `ω` fragment.
-/
import Mathlib
import RGF.Math.SetTheory.RGF2.Core.WType
import RGF.Math.SetTheory.RGF2.Core.InternalOrdinal
import RGF.Math.SetTheory.RGF2.Hierarchy.Transfinite

open Ordinal

universe u

namespace RGF
namespace RGF2

/-
**Finite generative fragment.** Iterating the internal von Neumann successor
`succOrd₂` `n` times from the internal empty set `toRGFOrd 0` yields the internal
finite ordinal `n`.
-/
theorem iterate_succOrd₂_eq_toRGFOrd (n : ℕ) :
    (succOrd₂^[n]) (toRGFOrd (0 : Ordinal.{u})) = toRGFOrd (n : Ordinal.{u}) := by
  induction n <;> simp_all +decide [ Function.iterate_succ_apply' ];
  convert succOrd₂_toRGFOrd _

/-
**The bridge.** The transfinite generative flow (with *any* limit aggregation
rule `lim`) coincides at each finite stage `n` with the internal set-theoretic
ordinal `n`.  Thus, on the finite fragment, "step iteration dynamics" and the
"internal set universe" are one and the same construction.
-/
theorem tfIterate_succOrd₂_eq_toRGFOrd
    (lim : (o : Ordinal.{u}) → Order.IsSuccLimit o → (Π o' < o, RGFSet₂.{u}) → RGFSet₂.{u})
    (n : ℕ) :
    tfIterate succOrd₂ (toRGFOrd (0 : Ordinal.{u})) lim (n : Ordinal.{u})
      = toRGFOrd (n : Ordinal.{u}) := by
  rw [tfIterate_natCast]
  exact iterate_succOrd₂_eq_toRGFOrd n

/-
**Generation completeness for `ω`.** An internal set belongs to the internal
`ω` (`omegaOrd₂`) iff it is a finite iterate of the generative step from the seed.
So the internal `ω` is precisely the orbit generated by the step dynamics.
-/
theorem mem_omegaOrd₂_iff_iterate (z : RGFSet₂.{u}) :
    Mem₂ z omegaOrd₂ ↔ ∃ n : ℕ, z = (succOrd₂^[n]) (toRGFOrd (0 : Ordinal.{u})) := by
  constructor;
  · intro hz
    have h_equiv : ∃ n : ℕ, equivZF z = (n : Ordinal).toZFSet := by
      have h_equiv : ∃ a : Ordinal, a < Ordinal.omega0 ∧ a.toZFSet = equivZF z := by
        convert Ordinal.mem_toZFSet_iff.mp _;
        convert hz using 1;
        simp +decide [ Mem₂, omegaOrd₂ ];
      obtain ⟨ a, ha₁, ha₂ ⟩ := h_equiv; rw [ Ordinal.lt_omega0 ] at ha₁; obtain ⟨ n, rfl ⟩ := ha₁; exact ⟨ n, ha₂.symm ⟩ ;
    -- By definition of `toRGFOrd`, we know that `equivZF (toRGFOrd n) = n.toZFSet`.
    obtain ⟨n, hn⟩ := h_equiv;
    have h_eq : z = toRGFOrd n := by
      exact equivZF.injective <| by aesop;
    exact ⟨ n, h_eq.trans ( iterate_succOrd₂_eq_toRGFOrd n ▸ rfl ) ⟩;
  · rintro ⟨ n, rfl ⟩;
    convert toRGFOrd_mem_iff.mpr _;
    convert iterate_succOrd₂_eq_toRGFOrd n;
    exact Ordinal.nat_lt_omega0 n

end RGF2
end RGF