/-
  Modern/MeasureIntegration.lean

  **Measure theory and integration on the RGF real line.**

  Equipped with the metric/topology instances from `Modern.RealInstances`, the
  RGF reals carry their Borel σ-algebra, and we construct an honest measure on
  `RGFReal'` — the push-forward of Lebesgue measure under the order/ring
  isomorphism — together with Bochner integration against it.  This directly
  addresses the criticism that the self-built reals had "no measure or integral".

  Concretely we:

  * register the Borel `MeasurableSpace` / `BorelSpace` on `RGFReal'`;
  * define `rgfVolume`, the Lebesgue measure on the RGF real line;
  * compute the measure of the unit interval `[0,1]` to be `1`;
  * evaluate a Bochner integral `∫ x ∈ [0,1], 1 ∂rgfVolume = 1` on the RGF line.
-/
import Mathlib
import RGF.Math.Real.RGFRealExamples
import RGF.Math.Real.RealInstances

namespace RGF
namespace RGFReal'

open MeasureTheory

/-! ## Borel measurable structure -/

/-- The Borel σ-algebra on the RGF reals (generated by the metric topology). -/
instance instMeasurableSpace : MeasurableSpace RGFReal' := borel _

instance instBorelSpace : BorelSpace RGFReal' := ⟨rfl⟩

/-! ## The canonical embedding `ℝ → RGFReal'` is a measurable isomorphism -/

/-
`ofReal` coincides with the inverse of the isometry `toReal`.
-/
theorem ofReal_eq_isometrySymm : (ofReal : ℝ → RGFReal') = isometryEquivReal.symm := by
  funext x; apply RGFReal'.toReal_injective; simp [toReal_ofReal];
  convert isometryEquivReal.apply_symm_apply x |> Eq.symm

/-
`ofReal : ℝ → RGFReal'` is continuous (it is the inverse of an isometry).
-/
theorem continuous_ofReal : Continuous (ofReal : ℝ → RGFReal') := by
  rw [ofReal_eq_isometrySymm]
  exact isometryEquivReal.symm.continuous

/-- `ofReal : ℝ → RGFReal'` is measurable. -/
theorem measurable_ofReal : Measurable (ofReal : ℝ → RGFReal') :=
  continuous_ofReal.measurable

/-! ## Lebesgue measure on the RGF real line -/

/-- **Lebesgue measure on the RGF reals**, defined as the push-forward of the
    standard Lebesgue measure under the canonical embedding `ofReal`. -/
noncomputable def rgfVolume : Measure RGFReal' :=
  Measure.map (ofReal : ℝ → RGFReal') volume

/-
The preimage of an RGF interval `[a,b]` under `ofReal` is the real interval
    `[toReal a, toReal b]`.
-/
theorem preimage_ofReal_Icc (a b : RGFReal') :
    ofReal ⁻¹' Set.Icc a b = Set.Icc (toReal a) (toReal b) := by
  ext x;
  simp +decide [ Set.mem_Icc, ← RGFReal'.toReal_le_iff ]

/-
**The measure of the unit interval is `1`.**
-/
theorem rgfVolume_Icc_zero_one : rgfVolume (Set.Icc (0 : RGFReal') 1) = 1 := by
  convert Measure.map_apply measurable_ofReal ( measurableSet_Icc ) using 1;
  · rw [ preimage_ofReal_Icc ];
    rw [ toReal_zero, toReal_one, Real.volume_Icc ] ; norm_num;
  · constructor;
    convert isClosed_le ?_ ?_ using 1;
    all_goals try exact continuous_fst;
    · constructor;
      convert isClosed_le ( show Continuous fun p : RGFReal' × RGFReal' => p.1.toReal from ?_ ) ( show Continuous fun p : RGFReal' × RGFReal' => p.2.toReal from ?_ ) using 1;
      · ext; simp [toReal_le_iff];
      · convert isometryEquivReal.continuous.comp continuous_fst using 1;
      · convert isometryEquivReal.continuous.comp continuous_snd using 1;
    · exact continuous_snd

/-! ## Bochner integration on the RGF real line -/

/-
**A Bochner integral on the RGF line.** Integrating the constant function `1`
    over the unit interval of the RGF reals yields `1`.
-/
theorem rgf_integral_const_one :
    ∫ _x in Set.Icc (0 : RGFReal') 1, (1 : ℝ) ∂rgfVolume = 1 := by
  convert congr_arg ENNReal.toReal ( rgfVolume_Icc_zero_one ) using 1;
  norm_num;
  rfl

end RGFReal'
end RGF