/-
  Foundations/RGFInfinity.lean

  **The Axiom of Infinity and its relation to full ZFC, for the RGF reals.**

  The companion file `Foundations/RGFSetTheory.lean` shows that the generative
  reals `RGFReal'` carry the hereditarily finite universe `HF = (ℕ, ∈ₐ)` (the
  Ackermann model), a model of every Zermelo–Fraenkel axiom *except Infinity*.
  There it is recorded honestly (`not_infinity`) that the Infinity axiom genuinely
  fails: no single coded set is inductive.

  This file makes precise the *relation between the Infinity axiom and full ZFC*
  inside the RGF framework.  The honest mathematical situation is:

  * The proper-class universe `V` of full ZF cannot be a single set (it cannot
    live inside `ℝ`).  So one cannot literally "fit all of ZFC" into the reals.

  * What one *can* prove — and what we prove here — is the precise equivalence
    promised by the task: over the HF base (ZF − Infinity) the Infinity axiom is
    equivalent to a **bounded infinity principle**, namely that the von Neumann
    naturals generated by the successor operation are *bounded by a single code*
    (`infinity_iff_bounded`).  Both sides genuinely fail in `HF`
    (`no_inductive_set`, `not_boundedInfinity`): the naturals are produced one at
    a time but never collected into one finite set.

  * The **generation process** of the RGF reals nevertheless realizes the
    von Neumann naturals `RNat k = RVal (iter k)` as an *actual infinite* family
    of reals (`RNat_range_infinite`), inductive as a class:  `RNat 0` is empty and
    `RNat (k+1)` is the successor of `RNat k` (`rgf_bounded_infinity`).  This is the
    sense in which the RGF reals + generation model ZF − Infinity together with the
    *potential / bounded* infinity supplied by generation.
-/
import Mathlib
import RGF.Math.SetTheory.RGFSetTheory

namespace RGF
namespace RGFSet

open RGFReal'

/-! ## The von Neumann successor on Ackermann codes -/

/-- The von Neumann successor on codes: `succ n` codes `n ∪ {n}`. -/
def succ (n : ℕ) : ℕ := n ||| 2 ^ n

/-- The `n`-th binary digit of `n` is always `0` (since `n < 2 ^ n`). -/
theorem testBit_self (n : ℕ) : Nat.testBit n n = false :=
  Nat.testBit_eq_false_of_lt Nat.lt_two_pow_self

/-- Membership into a successor: `c ∈ succ n ↔ c = n ∨ c ∈ n`. -/
theorem mem_succ (c n : ℕ) : Mem c (succ n) ↔ (c = n ∨ Mem c n) := by
  unfold Mem succ
  rw [Nat.testBit_or, Nat.testBit_two_pow, Bool.or_eq_true, decide_eq_true_eq]
  tauto

/-- `n` is a member of its own successor. -/
theorem self_mem_succ (n : ℕ) : Mem n (succ n) := (mem_succ n n).2 (Or.inl rfl)

/-- Members are preserved by taking the successor. -/
theorem mem_succ_of_mem {c n : ℕ} (h : Mem c n) : Mem c (succ n) := (mem_succ c n).2 (Or.inr h)

/-- The successor strictly increases the code. -/
theorem lt_succ (n : ℕ) : n < succ n := by
  have hle : n ≤ succ n := Nat.left_le_or
  rcases lt_or_eq_of_le hle with h | h
  · exact h
  · exfalso
    have hb : Nat.testBit (succ n) n = true := self_mem_succ n
    rw [← h, testBit_self] at hb
    exact Bool.false_ne_true hb

/-! ## The generated von Neumann naturals -/

/-- The von Neumann naturals as codes: `iter k` codes `{iter 0, …, iter (k-1)}`,
    i.e. the `k`-th finite ordinal.  This is the *generation process* for `ω`. -/
def iter : ℕ → ℕ
  | 0 => 0
  | k + 1 => succ (iter k)

theorem iter_succ (k : ℕ) : iter (k + 1) = succ (iter k) := rfl

/-- The generated naturals grow at least linearly, hence are unbounded. -/
theorem le_iter (k : ℕ) : k ≤ iter k := by
  induction k with
  | zero => exact Nat.zero_le _
  | succ k ih =>
    have := lt_succ (iter k)
    rw [iter_succ]; omega

/-- `iter` is strictly monotone. -/
theorem iter_strictMono : StrictMono iter :=
  strictMono_nat_of_lt_succ (fun n => by rw [iter_succ]; exact lt_succ _)

/-- The members of `iter k` are exactly the previously generated naturals:
    `iter k = {iter j | j < k}`. -/
theorem mem_iter (c k : ℕ) : Mem c (iter k) ↔ ∃ j, j < k ∧ c = iter j := by
  induction k with
  | zero =>
      constructor
      · intro h; exact absurd h (empty c)
      · rintro ⟨j, hj, _⟩; omega
  | succ k ih =>
      rw [iter_succ, mem_succ, ih]
      constructor
      · rintro (rfl | ⟨j, hj, rfl⟩)
        · exact ⟨k, Nat.lt_succ_self k, rfl⟩
        · exact ⟨j, Nat.lt_succ_of_lt hj, rfl⟩
      · rintro ⟨j, hj, rfl⟩
        rcases Nat.lt_succ_iff_lt_or_eq.1 hj with h | h
        · exact Or.inr ⟨j, h, rfl⟩
        · exact Or.inl (by rw [h])

/-! ## Infinity fails as a set, and is equivalent to a bounded principle -/

/-- A set `z` is **inductive** if it contains `∅` and is closed under successor. -/
def Inductive (z : ℕ) : Prop := Mem 0 z ∧ ∀ y, Mem y z → Mem (succ y) z

/-- Every generated natural lies in any inductive set. -/
theorem iter_mem_of_inductive {z : ℕ} (hz : Inductive z) (k : ℕ) : Mem (iter k) z := by
  induction k with
  | zero => exact hz.1
  | succ k ih => rw [iter_succ]; exact hz.2 _ ih

/-- **The Axiom of Infinity fails internally**: no coded HF set is inductive. -/
theorem no_inductive_set : ¬ ∃ z, Inductive z := by
  rintro ⟨z, hz⟩
  have h := iter_mem_of_inductive hz z
  have hlt := testBit_lt z (iter z) h
  have hge := le_iter z
  omega

/-- The **bounded infinity principle**: the von Neumann naturals generated by the
    successor operation are bounded by a single code.  Adding this to ZF − Infinity
    is exactly what is needed to recover the Infinity axiom (`infinity_iff_bounded`). -/
def BoundedInfinity : Prop := ∃ B, ∀ k, iter k ≤ B

/-- The bounded infinity principle also fails in `HF`: the generated naturals are
    genuinely unbounded. -/
theorem not_boundedInfinity : ¬ BoundedInfinity := by
  rintro ⟨B, hB⟩
  have h1 := hB (B + 1)
  have h2 := le_iter (B + 1)
  omega

/-- **Equivalence promised by the task.**  Over the HF base (ZF − Infinity), the
    Axiom of Infinity (existence of an inductive set) is equivalent to the bounded
    infinity principle.  Both genuinely fail in `HF`, so the equivalence pins down
    exactly the missing ingredient: an actual *bound* collecting all the generated
    naturals into one set. -/
theorem infinity_iff_bounded : (∃ z, Inductive z) ↔ BoundedInfinity := by
  constructor
  · rintro ⟨z, hz⟩
    exact ⟨z, fun k => le_of_lt (testBit_lt z (iter k) (iter_mem_of_inductive hz k))⟩
  · intro h; exact absurd h not_boundedInfinity

/-! ## The generation process realizes `ω` inside the RGF reals -/

/-- The generation process realizing the von Neumann naturals as RGF reals. -/
noncomputable def RNat (k : ℕ) : RGFReal' := RVal (iter k)

theorem RNat_injective : Function.Injective RNat :=
  fun _ _ h => iter_strictMono.injective (RVal_injective h)

theorem RNat_mem_univ (k : ℕ) : RNat k ∈ Univ := RVal_mem_univ (iter k)

/-- The generated naturals form an actually infinite family of RGF reals. -/
theorem RNat_range_infinite : (Set.range RNat).Infinite :=
  Set.infinite_range_of_injective RNat_injective

theorem RNat_range_subset_univ : Set.range RNat ⊆ Univ := by
  rintro x ⟨k, rfl⟩; exact RNat_mem_univ k

/-- `RNat 0` is the empty set. -/
theorem RNat_zero_empty : ∀ c ∈ Univ, ¬ RMem c (RNat 0) := by
  rintro c ⟨n, rfl⟩
  rw [show RNat 0 = RVal 0 from rfl, RMem_RVal]
  exact empty n

/-- `RNat (k+1)` is the von Neumann successor of `RNat k`, transported to the reals. -/
theorem RMem_RNat_succ (x : RGFReal') (hx : x ∈ Univ) (k : ℕ) :
    RMem x (RNat (k + 1)) ↔ (x = RNat k ∨ RMem x (RNat k)) := by
  obtain ⟨c, rfl⟩ := hx
  unfold RNat
  rw [iter_succ, RMem_RVal, mem_succ, RMem_RVal]
  constructor
  · rintro (h | h)
    · exact Or.inl (by rw [h])
    · exact Or.inr h
  · rintro (h | h)
    · exact Or.inl (RVal_injective h)
    · exact Or.inr h

/-- **Resolution of Infinity for the RGF reals.**

    (i)  No real coding an HF set is inductive: the Infinity axiom, read as a
         statement about a single set, fails internally (`no_inductive_set`).
    (ii) Yet the generation process realizes the von Neumann naturals `RNat` as an
         *actual infinite* family of RGF reals, inductive as a class: `RNat 0` is
         empty and `RNat (k+1)` is the successor of `RNat k`.

    Together these say precisely that the RGF reals model ZF − Infinity (the
    internal HF universe) together with the bounded / potential infinity principle
    supplied by the generation process. -/
theorem rgf_bounded_infinity :
    (¬ ∃ z, Inductive z) ∧
    (Set.range RNat).Infinite ∧
    (∀ c ∈ Univ, ¬ RMem c (RNat 0)) ∧
    (∀ x ∈ Univ, ∀ k, RMem x (RNat (k + 1)) ↔ (x = RNat k ∨ RMem x (RNat k))) :=
  ⟨no_inductive_set, RNat_range_infinite, RNat_zero_empty,
    fun x hx k => RMem_RNat_succ x hx k⟩

end RGFSet
end RGF
